"use strict";
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (Object.hasOwnProperty.call(mod, k)) result[k] = mod[k];
    result["default"] = mod;
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
const os_1 = require("os");
const path = __importStar(require("path"));
exports.dockerServerRoot = `/_server_`;
const home = os_1.homedir();
const cwd = process.cwd();
exports.smaPath = p => path.join(home, '.sma', p);
exports.localPath = p => path.join(cwd, p);
exports.localWorldsPath = () => exports.localPath('worlds');
exports.smaWorldsPath = () => exports.smaPath('worlds');
exports.localWorldPath = p => path.join(exports.localWorldsPath(), p);
exports.smaWorldPath = p => path.join(exports.smaWorldsPath(), p);
exports.pluginsPath = () => exports.localPath('node_modules');
