"use strict";
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (Object.hasOwnProperty.call(mod, k)) result[k] = mod[k];
    result["default"] = mod;
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
var os_1 = require("os");
var path = __importStar(require("path"));
var home = os_1.homedir();
var cwd = process.cwd();
exports.smaPath = function (p) { return path.join(home, '.sma', p); };
exports.localPath = function (p) { return path.join(cwd, p); };
exports.localWorldsPath = function () { return exports.localPath('worlds'); };
exports.smaWorldsPath = function () { return exports.smaPath('worlds'); };
exports.localWorldPath = function (path) { return exports.localWorldsPath() + "/" + path; };
exports.smaWorldPath = function (path) { return exports.smaWorldsPath() + "/" + path; };
exports.pluginsPath = function () { return exports.localPath('node_modules'); };
